steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecommerce-api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-api']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ecommerce-api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ecommerce-api'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
images:
- 'gcr.io/$PROJECT_ID/ecommerce-api'

# Substitution variables
substitutions:
  _OPENAI_API_KEY: '' # This will be provided at build time
